apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddos-platform.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ddos-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
  - port: {{ .Values.service.api.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend
